services:
  nginx_proxy:
    image: nginx:latest
    container_name: http_only_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-http-only.conf:/etc/nginx/conf.d/default.conf
      - /etc/cloudflare/origin-certs:/etc/nginx/certs:ro
    networks:
      - scaletrailnet
volumes:
  cloudflare_cert:
    external: true
networks:
  scaletrailnet:
    external: true