services:
  backend_prod:
    image: ghcr.io/[your-github-username]/[your-backend-repo]:main
    env_file: .env.prod
    command: gunicorn scaletrail_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_prod:/app/backend/static_prod
    expose:
      - "8000"  # Exposed only to internal NGINX
    networks:
      - scaletrailnet

  nginx_prod:
    image: nginx:latest
    depends_on:
      - backend_prod
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - static_prod:/app/backend/static_prod
      - /etc/cloudflare/origin-certs:/etc/nginx/certs:ro
    expose:
      - "80"
      - "443"
    networks:
      - scaletrailnet